[theme]
primaryColor = "#3498db"
backgroundColor = "#ecf0f1"
secondaryBackgroundColor = "#bdc3c7"
textColor = "#2c3e50"
font = "sans serif"

[server]
maxUploadSize = 200
maxMessageSize = 200
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[global]
developmentMode = false
